# Naive Bayesian

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("breast_cancer.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

### Dependent and Independent Variables

In [3]:
x = df.iloc[:,2:-1]
y = df.iloc[:,1]

## Spliting test and train Data

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

## Modeling Naive Bayesian 

In [5]:
sum_p = (y_train == 'M').sum()
sum_n = (y_train == 'B').sum()
print(sum_p, sum_n, sum_p + sum_n)

162 293 455


### Baseline Prediction

In [6]:
baseline_pred = ['B'] * len(y_train)

from sklearn import metrics

print("Acurracy\t\t: ", metrics.accuracy_score(y_train, baseline_pred))
print("Confusion Matrix\t: \n\n", metrics.confusion_matrix(y_train, baseline_pred))
print("Classification Report\t:\n\n", metrics.classification_report(y_train, baseline_pred))

Acurracy		:  0.643956043956044
Confusion Matrix	: 

 [[293   0]
 [162   0]]
Classification Report	:

               precision    recall  f1-score   support

           B       0.64      1.00      0.78       293
           M       0.00      0.00      0.00       162

    accuracy                           0.64       455
   macro avg       0.32      0.50      0.39       455
weighted avg       0.41      0.64      0.50       455



/Users/Ataago/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Naive Bayes Algorithmm

In [7]:
from sklearn import naive_bayes

my_model = naive_bayes.GaussianNB()
my_model.fit(x_train, y_train)

y_hat = my_model.predict(x_test)

### Evaluation

In [8]:
print("Confusion Matrix for Training Data: \n\n", metrics.confusion_matrix(y_train, my_model.predict(x_train)))
print("\nConfusion Matrix for Testing Data: \n\n", metrics.confusion_matrix(y_test, y_hat))
print("\nClassification Report Training Data:\n\n", metrics.classification_report(y_train, my_model.predict(x_train)))
print("\nClassification Report Testing Data:\n\n", metrics.classification_report(y_test, y_hat))

Confusion Matrix for Training Data: 

 [[284   9]
 [ 20 142]]

Confusion Matrix for Testing Data: 

 [[63  1]
 [ 3 47]]

Classification Report Training Data:

               precision    recall  f1-score   support

           B       0.93      0.97      0.95       293
           M       0.94      0.88      0.91       162

    accuracy                           0.94       455
   macro avg       0.94      0.92      0.93       455
weighted avg       0.94      0.94      0.94       455


Classification Report Testing Data:

               precision    recall  f1-score   support

           B       0.95      0.98      0.97        64
           M       0.98      0.94      0.96        50

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



### Predicting Train and Test wrt Probablities greater than 0.25 as Malignant

In [9]:
pred_train = my_model.predict_proba(x_train)[:,1] > 0.25
pred_test = my_model.predict_proba(x_test)[:,1] > 0.25

print("Confusion matrix Train Data: \n\n", metrics.confusion_matrix(y_train == 'M', pred_train))
print("\nConfusion matrix Test Data: \n\n", metrics.confusion_matrix(y_test == 'M', pred_test))

Confusion matrix Train Data: 

 [[282  11]
 [ 19 143]]

Confusion matrix Test Data: 

 [[63  1]
 [ 2 48]]
